DROP TABLE IF EXISTS SUCURSALES;
DROP TABLE IF EXISTS PROVEEDORES;
DROP TABLE IF EXISTS CORREOS_PROV;
DROP TABLE IF EXISTS TELEFONOS_PROV;
DROP TABLE IF EXISTS VEHICULOS;

CREATE TABLE PROVEEDORES(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50),
	DIRECCION VARCHAR(150),
	SALDO INT,
	FECHA_ULTIMO_PEDIDO TIMESTAMP,
	
	ACTIVO BOOL DEFAULT TRUE,
	CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ELIMINACION TIMESTAMP,
    MODIFICACION TIMESTAMP
);

CREATE TABLE TELEFONOS_PROV(
	PROVEEDOR_ID INT,
	NUMERO_TELEFONO VARCHAR(20),
	
	ACTIVO BOOL DEFAULT TRUE,
	CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ELIMINACION TIMESTAMP,
    MODIFICACION TIMESTAMP,
	
	PRIMARY KEY (PROVEEDOR_ID, NUMERO_TELEFONO),
	FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES (ID)
);

CREATE TABLE CORREOS_PROV(
	PROVEEDOR_ID INT,
	CORREO VARCHAR(100),
	
	ACTIVO BOOL DEFAULT TRUE,
	CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ELIMINACION TIMESTAMP,
    MODIFICACION TIMESTAMP,
	
	PRIMARY KEY (PROVEEDOR_ID, CORREO),
	FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES (ID)
);

CREATE TABLE SUCURSALES (
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	
	ACTIVO BOOL DEFAULT TRUE,
	CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ELIMINACION TIMESTAMP,
    MODIFICACION TIMESTAMP
);

CREATE TABLE VEHICULOS (
	CHASIS VARCHAR(50) PRIMARY KEY,
	SUCURSAL_ID INT,
	PROVEEDOR_ID INT,
	PATENTE VARCHAR (10),
	CONDICION VARCHAR (10),
	MARCA VARCHAR (50),
	VERSION VARCHAR (50),
	ANIO INT,
	PRECIO INT,
	KILOMETRAJE INT,
	ESTADO VARCHAR (50),
	
	ACTIVO BOOL DEFAULT TRUE,
	CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ELIMINACION TIMESTAMP,
    MODIFICACION TIMESTAMP,
	
	FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID),
	FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES (ID)
);